import type { Metadata } from "next";
import SidebarForAdmin from "@/app/components/sidebar/SidebarForAdmin";
import Header from "@/app/components/Header";
import UserListForAdmin from "@/app/components/user/UserListForAdmin";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
	return (
		<div>
			<Header />
			<div className="flex mt-[60px]"> {/* 画面全体を高さを使用 */}
				{/* サイドバー部分 */}
				<div className="w-70 max-h-screen fixed border border-r-1 border-gray-300">
					<SidebarForAdmin />
				</div>

				{/* メインコンテンツ部分 */}
				<div className="flex-1 max-h-screen ml-[17.5rem]">
					<UserListForAdmin />
				</div>
			</div>
		</div>
	);
  }