import type { Metadata } from "next";
import Sidebar from "@/app/components/Sidebar";
import LessonContent from "@/app/components/LessonContent";
import Header from "@/app/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
	return (
		<div>
			<Header />
			<div className="flex mt-15"> {/* 画面全体を高さを使用 */}
				{/* サイドバー部分 */}
				<div className="w-120 max-h-screen fixed overflow-y-auto border border-r-1 border-gray-300">
					<Sidebar />
				</div>

				{/* メインコンテンツ部分 */}
				<div className="flex-1 max-h-screen ml-[30rem]">
					<LessonContent />
				</div>
			</div>
		</div>
	);
  }