import type { Metadata } from "next";
import { Noto_Sans_JP  } from "next/font/google";
import Header from "@/app/components/Header";
import "./globals.css";

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSansJp.className} pt-11 pb-10`}>
		<Header />
        {children}
      </body>
    </html>
  );
}
