import type { Metadata } from "next";
import LessonListSidebar from "@/app/components/sidebar/LessonListSidebar";
import LessonDetail from "@/app/components/lesson/LessonDetail";
import Header from "@/app/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
	return (
		<div>
			<Header />
			<div className="flex mt-[60px]">
				{/* サイドバー部分 */}
				<div className="w-120 max-h-screen fixed overflow-y-auto border border-r-1 border-gray-300">
					<LessonListSidebar />
				</div>

				{/* メインコンテンツ部分 */}
				<div className="flex-1 max-h-screen ml-[30rem]">
					<LessonDetail />
				</div>
			</div>
		</div>
	);
  }